# Generated by Django 2.1.5 on 2019-03-15 04:34

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_created_at', models.CharField(blank=True, max_length=60)),
                ('tweet_id', models.CharField(max_length=60)),
                ('tweet_text', models.TextField()),
                ('tweet_user', models.CharField(max_length=60)),
                ('tweet_longitude', models.FloatField(blank=True, default=None, null=True)),
                ('tweet_latitude', models.FloatField(blank=True, default=None, null=True)),
                ('tweet_place', jsonfield.fields.JSONField(blank=True, default=None)),
                ('tweet_retweeted_status', models.BooleanField(blank=True, default=False)),
                ('tweet_media', jsonfield.fields.JSONField(blank=True)),
                ('tweet_hashtags', jsonfield.fields.JSONField(blank=True)),
                ('tweet_possibly_sensitive', models.BooleanField(blank=True, default=False)),
                ('tweet_score', models.FloatField(blank=True, null=True)),
                ('tweet_user_screen_name', models.CharField(default=None, max_length=20)),
                ('tweet_user_user_name', models.CharField(default=None, max_length=60)),
                ('tweet_user_location', models.CharField(blank=True, default=None, max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=60)),
                ('t_screen_name', models.CharField(max_length=20)),
                ('t_user_name', models.CharField(max_length=60)),
                ('t_user_location', models.CharField(blank=True, max_length=240, null=True)),
                ('t_user_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
