# Generated by Django 2.1.5 on 2019-03-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_user_screen_name',
        ),
    ]
