# Generated by Django 2.1.5 on 2019-02-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190220_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
