# Generated by Django 2.1.5 on 2019-03-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190315_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
