# Generated by Django 2.1.5 on 2019-03-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190318_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_created_at',
            field=models.DateTimeField(blank=True, max_length=60),
        ),
    ]
