# Generated by Django 2.1.5 on 2019-03-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190312_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_user',
            name='t_user_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitter_user',
            name='t_user_location',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
