# Generated by Django 2.1.7 on 2019-03-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190326_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_user',
            name='t_user_gender',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
